In [3]:
import numpy as np

# Printing Arrays

When you print array, NumPy displays it in a similar way to nestead lists,but with the following layouts: 
 - The  last axis is printed from the left to the right
 - The seconf-to-last is printed from top to buttom
 - The rest are also printed from the top to the buttom, with each slice separated from the next by an empty line 

In [4]:
# One dimensional arrays are the printed as rows, bidimensionals as matrices are tridimesionals as lists of matrices

In [5]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [8]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
# Note  :  if any array is too large to be printed, NumPy automatically skips the central part of the array
#          and only prints the corners

In [12]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [14]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [15]:
# To disable this behaviour and force NumPy to print the entier array, you can change the printing options using 
# set_printoption


In [18]:
np.set_printoptions(threshold-sys.maxsize) #!!!!

NameError: name 'threshold' is not defined

# Basic operations

Arithmetic operations on arrays apply elementwise, a new array is created and filled with the result

In [22]:
a = np.array([20,30,40,50])
b = np.arange(4)
c = a-b
c
b**2
10*np.sin(a)
a<35

array([ True,  True, False, False])

Unlike in many matrix languages, the product operator * operates  elementwise in NumPy arrays, The matrix product can be performed using the @ operator or the dot fucntion

In [23]:
A = np.array([
              [1,1],[0,1]
             ])
B = np.array([
              [2,0],[3,4]
             ])
A*B # elementwise product

array([[2, 0],
       [0, 4]])

In [24]:
A@B #matrix product

array([[5, 4],
       [3, 4]])

In [25]:
A.dot(B) # another way to do matrix product 

array([[5, 4],
       [3, 4]])

let's do some math here :
In NumPy, there are two main ways to perform multiplication with matrices
- Elementwise Multiplication *
- Matrix Multiplication
* Elementwise multiplication (Hadamard product)
    - Use the * operator or np.multiply()
    - Multiplies corresponding elements of two matrices element by element
    - Requires both matrices to have to same shape
* Matrix Product (Dot Product or Matrix Multiplication)
    - Use the @ operator or dot()
    - Follow linear algebra matrix multiplication rules
        :
          - The number of columns in the first matrix must match the number of rows in the second matrix
          - The  resulting matrix has the shape (row of the first matrice, columns of the second matrie)
    


In [26]:
# Some operations such ass += , *= act in place to modify an existing array rather than create a new one


In [28]:
a = np.ones((2,3),dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [36]:
b += a
b

array([[6.98244639, 6.11675151, 6.50117754],
       [6.29409174, 6.23660633, 6.08231713]])