In [3]:
import numpy as np


In [4]:
# NumPy's main objective is the homogeneous multidimensional array.
# IT is a table of elements ( usually numbers) a;; of the same type , indexed by a tuple
# of non negative integers


In NumPy dimensions are called # Axed

In [5]:
# NumPy's array class is called ndarray 

It is knwon by the alias array, Not that numpy.array is not the same as the Standard Python
 Libraru class array.array  which only handle one dimensional arrays and offers less functionality
 the more important attributes of the ndarray object are :
 - ndarray.ndim : the number of axes (dimensions) of the array
 - ndarray.shape :  the dimensions of array, this is a tuple of integers indicating the size of array in each dimension Ex :  in a matrix(n,m) the length of the shape tuple therefore the number of axes  , ndim
 - ndarray.size : the total number of elements of the array, this is equal to the product of the element shape
 - ndarray.dtype an object describing the type of elements in the array , one can create or specify dtype's using standard Python types Additionally NumPy provides types of its own, numpy.int32. numpy.int64...
 - ndarray.itemsize the size in bytes of each element of the array
 - ndarray.data the buffer containing the actual elements of the array, usually we won't need to use this attributes because we will access the elements in an array using the indexing facilities

In [6]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
a.shape

(3, 5)

In [8]:
a.ndim #we have to understand this more?

2

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

#  Array Creation

There are several way to create an array

In [13]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [14]:
a.dtype

dtype('int64')

In [15]:
# The function zeros creates an array full of zeros, the function  ones create an array full of ones, and the function empty creates an array whose initial content is randomand depends on the state of 
# memory. By default , the dtype of the created array is float


In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [18]:
np.empty((2,3))

array([[4.65156928e-310, 0.00000000e+000, 4.65266108e-310],
       [4.65266154e-310, 0.00000000e+000, 0.00000000e+000]])

In [19]:
# To create sequences of numbers, NumPy provides a function  analogous to range that returns arrays instead of lists

In [20]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [21]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

NP: when arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite point precision, for this reason it is usually better to use the function linspace that receives as an argument the number of elements that we want, intsead of step:

In [22]:
from numpy import pi

In [23]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
x = np.linspace(0,2+pi,100)
x

array([0.        , 0.05193528, 0.10387056, 0.15580584, 0.20774112,
       0.2596764 , 0.31161168, 0.36354696, 0.41548223, 0.46741751,
       0.51935279, 0.57128807, 0.62322335, 0.67515863, 0.72709391,
       0.77902919, 0.83096447, 0.88289975, 0.93483503, 0.98677031,
       1.03870559, 1.09064087, 1.14257615, 1.19451142, 1.2464467 ,
       1.29838198, 1.35031726, 1.40225254, 1.45418782, 1.5061231 ,
       1.55805838, 1.60999366, 1.66192894, 1.71386422, 1.7657995 ,
       1.81773478, 1.86967006, 1.92160534, 1.97354061, 2.02547589,
       2.07741117, 2.12934645, 2.18128173, 2.23321701, 2.28515229,
       2.33708757, 2.38902285, 2.44095813, 2.49289341, 2.54482869,
       2.59676397, 2.64869925, 2.70063453, 2.7525698 , 2.80450508,
       2.85644036, 2.90837564, 2.96031092, 3.0122462 , 3.06418148,
       3.11611676, 3.16805204, 3.21998732, 3.2719226 , 3.32385788,
       3.37579316, 3.42772844, 3.47966372, 3.53159899, 3.58353427,
       3.63546955, 3.68740483, 3.73934011, 3.79127539, 3.84321

In [25]:
f  = np.sin(x)
f

array([ 0.        ,  0.05191194,  0.10368388,  0.15517623,  0.20625011,
        0.25676781,  0.30659309,  0.35559159,  0.40363118,  0.45058232,
        0.49631838,  0.54071603,  0.58365555,  0.62502115,  0.66470128,
        0.70258893,  0.73858192,  0.77258321,  0.8045011 ,  0.83424952,
        0.86174825,  0.88692312,  0.90970626,  0.93003623,  0.9478582 ,
        0.96312411,  0.97579279,  0.98583009,  0.99320893,  0.99790942,
        0.99991887,  0.99923188,  0.9958503 ,  0.98978323,  0.98104706,
        0.96966532,  0.95566872,  0.939095  ,  0.91998885,  0.8984018 ,
        0.87439206,  0.84802437,  0.81936985,  0.78850576,  0.75551533,
        0.72048752,  0.6835168 ,  0.64470287,  0.60415038,  0.56196871,
        0.51827159,  0.47317686,  0.42680614,  0.37928446,  0.33073997,
        0.2813036 ,  0.23110863,  0.18029045,  0.12898608,  0.07733388,
        0.02547314, -0.0264563 , -0.07831439, -0.1299613 , -0.18125774,
       -0.23206539, -0.28224724, -0.33166796, -0.38019428, -0.42

# Excercices 

* Create the following arrays using NumPy :
    - a) A 1D array containing the numbers 1,2,3,4,5
    - b) A 2D array of shape 2*3 with the elements 1,2,3,4,5,6
    - c) A 3D array of shape 2*2*2 with the values from  1 to 8

In [26]:
# The first one :  1D array conataining the number 1,2,3,4,5


In [28]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [29]:
# The second array : 2D array of the shape 2*3 with the elements 1,2,3,4,5,6

In [34]:
y = np.arange(1,7).reshape(2,3)
y

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# the third array : 3D array of shape (2*2*2) with values form 1 to 8

In [37]:
z = np.arange(1,9).reshape(2,2,2)
z

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

* Creating Arrays with functions
  - Use NumPy functions to generate the following arrays :
      - a) A 1D array of size 10 filled with zeros
      - b) A 1D array of size 10 filled with  ones
      - c) A 1D array of size 10 filled with the number 7
      - d) A 1D array containing numberd from 0 to 9
      - e) A 1D array conatining even numbers from 2 to 20
      - f) A 1D array containing 5number evenly spaced between 10 and 50 

In [38]:
# a) A 1D array of size 10 filled with zeros

In [40]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
# b) A 1D array of size 10 filled with ones

In [43]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
#A 1D array of size 10 filled with the number 7

In [54]:
# I dunno how 


In [55]:
# Here we have a function called full 

In [56]:
sevens_array = np.full(10,7)
sevens_array

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [46]:
#A 1D array containing numberd from 0 to 9

In [47]:
elem =  np.arange(0,10)
elem

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
#  A 1D array conatining even numbers from 2 to 20

In [50]:
elem1 = np.arange(2,21,2)
elem1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [51]:
# A 1D array containing 5number evenly spaced between 10 and 50

In [53]:
elem2 = np.arange(10,50,5)
elem2 # Wrong answer

array([10, 15, 20, 25, 30, 35, 40, 45])

In [58]:
# here we use linspace
linspace_array = np.linspace(10,50,5)
linspace_array

array([10., 20., 30., 40., 50.])

* Special Arrays
   - a) Create an identity matrix of size 4*4
   - b) Create a diagonal matrix with elements 1,2,3 along the diagonal
   - c) Create a 3*3 matrix filled with random numbers
   - d) Create a 4*4 matrix filled with random integers between 5 and 15

In [59]:
# a) Identity matrix (4*4)

In [60]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
# b) daigonal matrix

In [63]:
diagonal_matrix = np.diag([1,2,3,4])
diagonal_matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [64]:
# c) 3*3 matrix with random numbers

In [66]:
random_matrix = np.random.rand(3,3)
random_matrix

array([[0.06592004, 0.68518157, 0.88082289],
       [0.64698411, 0.69215048, 0.36632733],
       [0.07215595, 0.90142854, 0.62885255]])

In [67]:
# d) 4*4 matrix with random integers between 5 and 15

In [69]:
random_int_matrix = np.random.randint(5,16,(4,4))
random_int_matrix

array([[ 6, 12,  6, 13],
       [15, 13, 15, 14],
       [10,  5, 15,  6],
       [13, 14, 11,  7]])

* Reshaping Arrays
   - a) Create a 1D array of 12 elements and reshape  it into 3*4 matrix
   - b) Create a 1D array of 16 elements and reshape it into 4*4 matrix
   - c) Flatten a 3*3 matrix into a 1D array

In [72]:
resh_arr = np.arange(12).reshape(3,4)
resh_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
resha_arr1= np.random.randint(1,16,(4,4))
resha_arr1

array([[ 2,  5, 11, 15],
       [13,  3, 10,  2],
       [13,  2,  9,  8],
       [ 9, 13,  2, 12]])

In [77]:
# c) Flatten a 3×3 matrix
matrix_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flattened_array = matrix_3x3.flatten()
flattened_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])